/*
	DROPS DE LES TAULES PEL CREDIT DE SINTESI 2020
*/


DROP TABLE IF EXISTS RESPUESTA_USUARIO_HABITO;
DROP TABLE IF EXISTS RESPUESTA_HABITO;
DROP TABLE IF EXISTS INTERVALO_SINTOMA;
DROP TABLE IF EXISTS SINTOMA;
DROP TABLE IF EXISTS HABITO;
DROP TABLE IF EXISTS USUARIO;